Messages:
  SelfElectrocute:
  - &d$name$ is conducting themselves well
  - &d$name$ made a shocking discovery
  - &d$name$ decided to start lightening up
  SelfBurn:
  - &d$name$'s looking mighty crispy
  - &d$name$'s death warrants a study in Spontaneous Human Combustion
  - &d$name$ is all fired up and ready to go!
  Suicide:
  - &d$name$ couldn't take it anymore
  - &d$name$ was their own worst enemy
  - &d$name$ found no reason to continue
  Unknown:
  - '&dUnusual circumstances befell $name$'
  - '&d...yeah, $name$ does that sometimes'
  - '&dLooks like $name$ learned a new trick'
  KilledByLightning:
  - &d$name$ was struck down by $killer$
  KilledByFire:
  - &d$killer$ likes $name$ done medium-well
  KilledByEnergy:
  - &d$killer$ wouldn't quit poking $name$
  KilledByGust:
  - &d$name$ was cast into the abyss by $killer$
  KilledByVoid:
    AfterLightning:
    - &d$name$ thought the void was safer than $killer$'s lightning
    AfterFire:
    - &d$name$ used the void to extinguish $killer$'s fire
    AfterEnergy:
    - &d$name$ had just about enough of $killer$
    AfterGust:
    - &d$name$ couldn't get past $killer$'s gustiness
SpellSpawns: