GameMode: SURVIVAL
Messages:
  SelfElectrocute:
  - &d_name_ is conducting themselves well
  - &d_name_ made a shocking discovery
  - &d_name_ decided to start lightening up
  SelfBurn:
  - &d_name_'s looking mighty crispy
  - &d_name_'s death warrants a study in Spontaneous Human Combustion
  - &dLet _name_ cook!
  Suicide:
  - &d_name_ couldn't take it anymore
  - &d_name_ was their own worst enemy
  - &d_name_ found no reason to continue
  Unknown:
  - &dUnusual circumstances befell _name_
  - "&d...Yeah, _name_ does that sometimes..."
  - &dLooks like _name_ learned a new trick
  KilledByLightning:
  - &d_name_ was struck down by _killer_
  KilledByFire:
  - &d_killer_ likes _name_ done medium-well
  KilledByEnergy:
  - &d_killer_ wouldn't quit poking _name_
  KilledByGust:
  - &d_name_ was cast into the abyss by _killer_
  KilledByVoid:
    AfterLightning:
    - &d_name_ thought the void was safer than _killer_'s lightning
    AfterFire:
    - &d_name_ used the void to extinguish _killer_'s fire
    AfterEnergy:
    - &d_name_ had just about enough of _killer_
    AfterGust:
    - &d_name_ couldn't get past _killer_'s gustiness

